Update strings.xml
Mygod/VPNHotspot pull request #381
Opened 2022-05-25 16:47 UTC by Kaitul

Fixed some minor spelling and punctuation issues

2022-05-25 17:29 UTC, bluehomewu commented
> @bluehomewu thoughts?

I think some strings changes are unnecessary.
I'll point out the unnecessary parts later.

2022-05-25 17:42 UTC, bluehomewu requested changes

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="donations__google_android_market_donate_button">捐助！</string>
This part is an additional supplement to be more friendly to users. No need to update translations.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="donations__google_android_market_text">捐助多少錢</string>
This part is an additional supplement to be more friendly to users. No need to update translations.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="donations__thanks_dialog">感謝捐助！\n十分感謝您！</string>
This part is an additional supplement to be more friendly to users. No need to update translations.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="donations__description">這個應用程式有用嗎？\n小額的捐助給開發人員用來支援此應用程式的開發</string>
This part is an additional supplement to be more friendly to users. No need to update translations.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_misc_donate">捐助</string>
This part is an additional supplement to be more friendly to users. No need to update translations.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="repeater_wps">WPS (不安全)</string>
Chinese (Traditional) uses full-width punctuation, so it doesn't have to be changed.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="connected_state_incomplete">(正在連線)</string>
Chinese (Traditional) uses full-width punctuation, so it doesn't have to be changed.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="connected_state_valid">(已連線)</string>
Chinese (Traditional) uses full-width punctuation, so it doesn't have to be changed.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="connected_state_failed">(已中斷)</string>
Chinese (Traditional) uses full-width punctuation, so it doesn't have to be changed.

2022-05-25 17:42 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_misc_source_summary">閱讀手冊、加星號、提交問題並參與</string>
This part is an additional supplement to be more friendly to users.
But I suggest this part translations to
`閱讀使用說明，對 GitHub repo 加星號，提交問題並合作參與開發`

2022-05-25 18:06 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="repeater_wps">WPS (不安全)</string>
https://github.com/sparanoid/chinese-copywriting-guidelines#%E4%BD%BF%E7%94%A8%E5%85%A8%E5%BD%A2%E4%B8%AD%E6%96%87%E6%A8%99%E9%BB%9E

2022-05-25 18:07 UTC, bluehomewu commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_misc_logcat_summary">如此有用 (^0^)</string>
I can accept changes to symbols, but not their strings

2022-05-25 18:21 UTC, Kaitul commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="repeater_wps">WPS (不安全)</string>
But the fact is, Apple, Google, Microsoft are not using fullwidth brackets in the operating system and software Chinese translation.

Here are some examples copied from their website or app:
* 雲端硬碟、Gmail 和其他產品 (111.5 MB)
* 使用系統選擇 (預設)
* 允許將任何應用程式寫入外部儲存空間 (無論資訊清單值為何)
* Apple 與 Apple 的換購合作夥伴保留以任何理由拒絕或限制接受任何裝置 (及其數量) 參與本優惠。
* 此選項適用於想要建立可開機的安裝媒體 (USB 快閃磁碟機或 DVD) 或建立虛擬機器 (.ISO 檔案) 以安裝 Windows 11 的使用者。此下載是多版本 ISO，其使用您的產品金鑰解除鎖定正確的版本。

2022-05-25 18:53 UTC, pan93412 commented
@Kaitul There is no correct or wrong in terms of style; however, the consensus is essential: as the earliest translator, Edward has determined the translation style of this software in his translation. Even if his translation style does not match the translation guide of Microsoft or Google, his style should still be respected. Besides, this software is obviously not affiliated with Microsoft, Google, or even Apple – there is no reason to adopt the translation style specifications of these companies completely. Ultimately, if you are really dissatisfied with this style, it must be more appropriate to open an issue for a constructive discussion than change the styles without the original author's authorization.

2022-05-25 19:18 UTC, Kaitul commented
> @Kaitul There is no correct or wrong in terms of style; however, the consensus is essential: as the earliest translator, Edward has determined the translation style of this software in his translation. Even if his translation style does not match the translation guide of Microsoft or Google, his style should still be respected.
> 
> Besides, this software is obviously not affiliated with Microsoft, Google, or even Apple – there is no reason to adopt the translation style specifications of these companies completely. Ultimately, if you are really dissatisfied with this style, it must be more appropriate to open an issue for a constructive discussion than change the styles without the original author's authorization.

I'm sorry, I will respect Edward's translation style and revise the existing translation, please let me know if you have any requests.

I have changed some Chinese terms in the last version, this update is only a supplement to the last change, because zh-rTW seems to be a direct translation from zh-rCN.

2022-05-25 19:23 UTC, bluehomewu commented
> > @Kaitul There is no correct or wrong in terms of style; however, the consensus is essential: as the earliest translator, Edward has determined the translation style of this software in his translation. Even if his translation style does not match the translation guide of Microsoft or Google, his style should still be respected.
> > Besides, this software is obviously not affiliated with Microsoft, Google, or even Apple – there is no reason to adopt the translation style specifications of these companies completely. Ultimately, if you are really dissatisfied with this style, it must be more appropriate to open an issue for a constructive discussion than change the styles without the original author's authorization.
> 
> I'm sorry, I will respect Edward's translation style and revise the existing translation, please let me know if you have any requests.
> 
> I have changed some Chinese terms in the last version, this update is only a supplement to the last change, because zh-rTW seems to be a direct translation from zh-rCN.

I used English to translate, just because I noticed that the original author(@Mygod) maybe Chinese ( I'm not sure, just because he upload zh-rCN strings, so I guess) .
Therefore, some translations refer to the original author's own translation.Respect what the original author wanted to express

2022-05-25 19:31 UTC, Kaitul commented
> author

Sorry, I didn't think of that. I only have my phone in my hand now, I'll continue editing when I can, it's bedtime now, good night! :)

2022-05-25 20:15 UTC, Brli commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_misc_logcat_summary">如此有用 (^0^)</string>
Check that the original emojis of JP AA or TW BBS culture, where they mostly use full width

2022-05-25 21:05 UTC, Mygod commented on mobile/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_misc_logcat_summary">如此有用 (^0^)</string>
Personally I do prefer the previous version. 🙃

2022-05-25 21:07 UTC, Mygod commented
I agree with @pan93412. Let's stick with what native speakers of zh-rTW (e.g. @bluehomewu) suggest. Aesthetic styling is not an issue as long as it is consistent within the app.

2022-05-25 21:10 UTC, bluehomewu commented
> I agree with @pan93412. Let's stick with what native speakers of zh-rTW (e.g. @bluehomewu) suggest. Aesthetic styling is not an issue as long as it is consistent within the app.

Thanks>👍

2022-05-26 10:40 UTC, bluehomewu approved these changes

2022-05-26 22:26 UTC, merged

2022-05-26 22:26 UTC, Mygod commented
Merged. Thanks everyone!